### PR TITLE
Always load request_matcher and rule_matcher services

### LINKED ISSUE #193: issue when using symfony HttpCache cache
hi guys!
I have no varnish or nginx, I just trying to use symfony proxy cache with symfony built-in server and getting this error:
```
Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\RuntimeException' with message 'The parent definition "fos_http_cache.request_matcher" defined for definition "fos_http_cache.request_matcher.ea0361456f2444f1464abc61f1decd4b4215e2d10d07225889f2fba40bca65edd3622edf" does not exist.' in /Users/igor/PhpstormProjects/site.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php:67 Stack trace: #0 /Users/igor/PhpstormProjects/site.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php(50): Symfony\Component\DependencyInjection\Compiler\ResolveDefinitionTemplatesPass->resolveDefinition('fos_http_cache....', Object(Symfony\Component\DependencyInjection\DefinitionDecorator)) #1 /Users/igor/PhpstormProjects/site.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(119): Symfony\Component\DependencyInjection\Compiler\ResolveDefinitionTemplates in /Users/igor/PhpstormProjects/site.com/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php on line 67
503 Service Unavailable
```
```yaml
#app/config/config.yml
fos_http_cache:
    proxy_client:
        varnish:
            servers: 127.0.0.1:8005
            base_url: localhost:8005
    invalidation:
        enabled: true    # Defaults to 'auto'
        rules:
            -
                match:
                    attributes:
                        _route: "admin_archive_work_edit|admin_archive_work_delete"
                routes:
                    default_media_index: ~
```
```php
// app/AppCache.php
require_once __DIR__.'/AppKernel.php';

use FOS\HttpCacheBundle\SymfonyCache\EventDispatchingHttpCache;
use Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class AppCache extends EventDispatchingHttpCache
{
    protected function invalidate(Request $request, $catch = false)
    {
        if ('PURGE' !== $request->getMethod()) {
            return parent::invalidate($request, $catch);
        }

        if ('127.0.0.1' !== $request->getClientIp()) {
            return new Response('Invalid HTTP method', Response::$statusTexts[400]);
        }

        $response = new Response();
        if ($this->getStore()->purge($request->getUri())) {
            $response->setStatusCode(200, 'Purged');
        } else {
            $response->setStatusCode(200, 'Not found');
        }

        return $response;
    }
}
```
What's I'm doing wrong?

### PR DESCRIPTION
**Pull request by ddeboer**
Fix #193.

These services where previously defined in `cache_control_listener.xml`. That file, however, was not loaded e.g. when only invalidation (and no cache control) rules were defined. This PR always load the `request_matcher` and `rule_matcher`, so they can be used in `cache_control`, `invalidation` and/or `tags`.

### CODE REVIEW

File: DependencyInjection/FOSHttpCacheExtension.php [hunk 1]
```diff
@@ -43,6 +43,7 @@ public function load(array $configs, ContainerBuilder $container)
         $config = $this->processConfiguration($configuration, $configs);
 
         $loader = new XmlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
+        $loader->load('matcher.xml');
```
Comment (ddeboer) [inline DependencyInjection/FOSHttpCacheExtension.php]: I now simply always load `matcher.xml`, which means `rule_matcher` and `request_matcher` will be loaded even if they are not used. I don’t find this a big problem. We could make their loading optional, for instance in the `createRule|RequestMatcher()` methods.

Comment (dbu) [inline DependencyInjection/FOSHttpCacheExtension.php]: the services being private, they will be removed when the container is built, so this should have 0 runtime impact

**Comment by dbu** [comment]
something goes wrong with the tests. or is that coming from an update in the library and has nothing to do with the PR? i don't see the connection...

**Comment by dbu** [comment]
ping @ddeboer do we merge this one?

**Comment by ddeboer** [comment]
No, I need to fix the tests first. They fail locally as well.

**Comment by dbu** [comment]
now that you fixed tests in master, can you rebase this one?

**Comment by ddeboer** [comment]
Rebased.

**Comment by dbu** [comment]
still one failing test, i think because configuration test is not adjusted. can you check please?

**Comment by ddeboer** [comment]
Should be fixed now.
